import { Metadata } from "next"
import 'bootstrap/dist/css/bootstrap.min.css';
export const metadata: Metadata = {
  title: {

    default: 'shivank Tyagi',
    template: '%s | shivank',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "yellow", width: '100%' }}>
          <h1>
            Header
          </h1>
        </header>
        {children}
        <footer style={{ backgroundColor: 'blue', width: "100%" }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  )
}



